version: '3.8'
services:
  game:
    build: .
    command: python src/main.py
    volumes:
      - .:/app
    environment:
      - DISPLAY=:0  # Si usas X11 para Pygame localmente
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Puerto de acceso a la interfaz web de Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Puerto de acceso a la interfaz web de Grafana
    depends_on:
      - prometheus  # Grafana debe esperar a que Prometheus esté disponible

volumes:
  prometheus_data: # Para que guarde los datos de prometheus
  