global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
      
  - job_name: game
    static_configs:
      - targets: ["game:8000"]