global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['app:4000']  # Dirección del contenedor de la app Node.js
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']