name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt
        pip install behave pytest 

    - name: Run Unit Tests  #para pruwbas unitarias
      run: pytest tests/  
      

    - name: Run Behave Tests  #para pruebas de comportamiento
      run: behave tests/features/ 
