name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt

    - name: Run Unit Tests  #para pruwbas unitarias
      run: pytest tests/  
      

    - name: Run Behave Tests  #para pruebas de comportamiento
      run: behave tests/features/ 

    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version 

    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d 

    - name: Stop and clean Docker Compose
      run: |
        docker compose down
